project: fixmorph_bugs
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 0994b0a257557e18ee8f0b7c5f0f73fe2b54eec1
new_patch_parent: 0994b0a257557e18ee8f0b7c5f0f73fe2b54eec1^
target_release: 0a1af9ffc368e8860148a755b09a99ed01ff0a55
sanitizer: 
error_message: 
tag: 31