project: fixmorph_bugs
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 6d7225f0cc1a1fc32cf5dd01b4ab4b8a34c7cdb4
new_patch_parent: 6d7225f0cc1a1fc32cf5dd01b4ab4b8a34c7cdb4^
target_release: 0d669d90c1697fead43aafd33417a3a93a7f477c
sanitizer: 
error_message: 
tag: 303