project: fixmorph_bugs
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 01eca2842874b9a85b7cd1e1b0e5b34a5d53a21f
new_patch_parent: 01eca2842874b9a85b7cd1e1b0e5b34a5d53a21f^
target_release: 9447dabf5ea263c3a34a8d7c9f4e7b56259a558f
sanitizer: 
error_message: 
tag: 20