project: fixmorph_bugs
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: c93e64e91248becd0edb8f01723dff9da890e2ab
new_patch_parent: c93e64e91248becd0edb8f01723dff9da890e2ab^
target_release: 5dd3239f6b7c6fe644406a2f8d55156c4b4c3996
sanitizer: 
error_message: 
tag: 189