project: fixmorph_bugs
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 811a919135b980bac8009d042acdccf10dc1ef5e
new_patch_parent: 811a919135b980bac8009d042acdccf10dc1ef5e^
target_release: db01878ca5dd13ad51ff776309a6b75fd5867764
sanitizer: 
error_message: 
tag: 330