project: libtiff
project_url: https://github.com/libsdl-org/libtiff
new_patch: 6e2dac5f904496d127c92ddc4e56eccfca25c2ee
new_patch_parent: cb88a5b6bf1757060ec4d50055fa852fd7830cfe
target_release: c9db90c1a76c0f93da87c3ae32a6037c407b6d65
sanitizer: AddressSanitizer
error_massage: "ERROR: AddressSanitizer"
tag: CVE-2023-41175