project: bionic
project_url: https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/bionic/
new_patch: b739dffa5d570b411d4bdf4bb9b8dfd6b7d72305
new_patch_parent: b739dffa5d570b411d4bdf4bb9b8dfd6b7d72305^
target_release: b6df37dcb7d76f47a45a177df38478b8ec8d352b
sanitizer: 
error_message: 
tag: CVE-2024-46743
