project: focal
project_url: https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/focal/
new_patch: 6fef2d4c00b5b8561ad68dd2b68173f5c6af1e75
new_patch_parent: 6fef2d4c00b5b8561ad68dd2b68173f5c6af1e75^
target_release: 57bcefe21bd81e71f199f5cef2ca473e27e8bd00
sanitizer: 
error_message: 
tag: CVE-2024-26922