project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: cb66ddd156203daefb8d71158036b27b0e2caf63
new_patch_parent: f28cd2af22a0c134e4aa1c64a70f70d815d473fb
target_release: a04dde4e15d7b10752d64c2b56b3e36deeb4a45c
sanitizer: 
error_message: 
tag: CVE-2019-11815