project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: f5449e74802c1112dea984aec8af7a33c4516af1
new_patch_parent: 8383da3e4a610496c6790e46e48b2b26be0cc252
target_release: None
sanitizer: 
error_message: 
tag: CVE-2020-36385