project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: eb66ae030829605d61fbef1909ce310e29f78821
new_patch_parent: 19e6420e4170acce7a8651dfb87195dff5adbe72
target_release: 56a7ebd4a3adc001b18a8feeb5cdf0b9fb2684fa
sanitizer: 
error_message: 
tag: CVE-2018-18281