project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: fb18802a338b36f675a388fc03d2aa504a0d0899
new_patch_parent: f7c7d6ccc503c0a5f4e5debb570b55bf2eb24c73
target_release: 1a4d8b31b63428eb8193bce40ac40106cefabcbf
sanitizer: 
error_message: 
tag: CVE-2021-30002