project: fixmorph_bugs
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: cfd278c280f997cf2fe4662e0acab0fe465f637b
new_patch_parent: cfd278c280f997cf2fe4662e0acab0fe465f637b^
target_release: 0954c87c16bab5579b8c111887aafb6a75a17c0b
sanitizer: 
error_message: 
tag: 197