project: fixmorph_bugs
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 2e84eb9affac43eeaf834992888b72426a8cd442
new_patch_parent: 2e84eb9affac43eeaf834992888b72426a8cd442^
target_release: f730db608b65a131ecc2a2e57a743f904f77f765
sanitizer: 
error_message: 
tag: 66