project: bionic
project_url: https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/bionic/
new_patch: 6fef2d4c00b5b8561ad68dd2b68173f5c6af1e75
new_patch_parent: 6fef2d4c00b5b8561ad68dd2b68173f5c6af1e75^
target_release: b6df37dcb7d76f47a45a177df38478b8ec8d352b
sanitizer: 
error_message: 
tag: CVE-2024-26922