project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 04f5866e41fb70690e28397487d8bd8eea7d712a
new_patch_parent: dce5b0bdeec61bdbee56121ceb1d014151d5cab1
target_release: ed56c2497a3ecdf7ff0e0ff33a2bb80f74ebbc56
sanitizer: 
error_massage: 
tag: CVE-2019-11599