project: libtiff
project_url: https://github.com/libsdl-org/libtiff
new_patch: 82a7fbb1fa7228499ffeb3a57a1d106a9626d57c
new_patch_parent: ff049e353e5d7ef00a5400d285fc6f7dd498f39d
target_release: 66d6c6d1076979164d2bd1c5abcaed22bed6b202
sanitizer: AddressSanitizer
error_message: "ERROR: AddressSanitizer"
tag: CVE-2023-0800