project: linux
project_url: https://github.com/torvalds/linux/
new_patch: 462cdace790ac2ed6aad1b19c9c0af0143b6aab0
new_patch_parent: 462cdace790ac2ed6aad1b19c9c0af0143b6aab0^
target_release: 33bab9221e22bab4ddc167f6c49b6ca9c35c2ccf^
sanitizer: 
error_message: 
tag: CVE-2017-12134