project: fixmorph_bugs
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 8c3f9bd851a4d3acf0a0f222d4e9e41c0cd1ea8e
new_patch_parent: 8c3f9bd851a4d3acf0a0f222d4e9e41c0cd1ea8e^
target_release: 36b0779e9e289aeaf7efc7db977b1e4e5b95aaeb
sanitizer: 
error_message: 
tag: 143