project: fixmorph_bugs
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: d71f11c076c420c4e2fceb4faefa144e055e0935
new_patch_parent: d71f11c076c420c4e2fceb4faefa144e055e0935^
target_release: a461ae00464937f66812feae551c9e0526bce769
sanitizer: 
error_message: 
tag: 202