project: linux
project_url: https://github.com/torvalds/linux/
new_patch: b348d7dddb6c4fbfc810b7a0626e8ec9e29f7cbb
new_patch_parent: b348d7dddb6c4fbfc810b7a0626e8ec9e29f7cbb^
target_release: 7ce55b83fbf2ff341aacfe825001d40e7bbccbe2^
sanitizer: 
error_message: 
tag: CVE-2016-3955