project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: f1e255d60ae66a9f672ff9a207ee6cd8e33d2679
new_patch_parent: bba57eddadda936c94b5dccf73787cb9e159d0a5
target_release: c62b25af5f51f49e9f93f828cc38a82c23e8a0c5
sanitizer: 
error_message: 
tag: CVE-2018-16276