project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 04c2a47ffb13c29778e2a14e414ad4cb5a5db4b5
new_patch_parent: 6dde7acdb3dc2e0b3bcb090aac0b3699396d309f
target_release: 9892742f035f7aa7dcd2bb0750effa486db89576
sanitizer: 
error_message: 
tag: CVE-2022-1055