project: fixmorph_bugs
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 68202c9f0ad6e16ee806fbadbc5838d55fe5aa5c
new_patch_parent: 68202c9f0ad6e16ee806fbadbc5838d55fe5aa5c^
target_release: 8f5b7e3f415c208962b3fe4308486c4484d37b9f
sanitizer: 
error_message: 
tag: 115