project: ffmpeg
project_url: https://github.com/FFmpeg/FFmpeg
new_patch: 58aa0ed8f10753ee90f4a4a1f4f3da803cf7c145
new_patch_parent: b9f8ab3ef490738e7d459e2dbe1bfcb65a134d8e
target_release: 3d350ec7281cd0d357231fc2c99f44ebe425d586
sanitizer: AddressSanitizer
error_message: "ERROR: AddressSanitizer"
tag: CVE-2020-22016