project: fixmorph_bugs
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: f84598bd7c851f8b0bf8cd0d7c3be0d73c432ff4
new_patch_parent: f84598bd7c851f8b0bf8cd0d7c3be0d73c432ff4^
target_release: 9eae8ac6ab40b896b472c526afe7847e798f4f36
sanitizer: 
error_message: 
tag: 220