project: fixmorph_bugs
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 2cce76c3fab410520610a7d2f52faebc3cfcf843
new_patch_parent: 2cce76c3fab410520610a7d2f52faebc3cfcf843^
target_release: 93a443b33068176f332eabebe8da2060e983e18d
sanitizer: 
error_message: 
tag: 65