project: fixmorph_bugs
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: ec484d03ef0df8d34086b95710e355a259cbe1f2
new_patch_parent: ec484d03ef0df8d34086b95710e355a259cbe1f2^
target_release: 9fefd2252c8efca78f578d478acedb360b9bdd2c
sanitizer: 
error_message: 
tag: 215