project: fixmorph_bugs
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 1d18c2747f937f1b5ec65ce6bf4ccb9ca1aea9e8
new_patch_parent: 1d18c2747f937f1b5ec65ce6bf4ccb9ca1aea9e8^
target_release: 3f406ecddf8a8d4b6c2de195336ae1c6b56722c1
sanitizer: 
error_message: 
tag: 51