project: linux
project_url: https://github.com/torvalds/linux/
new_patch: e54ad7f1ee263ffa5a2de9c609d58dfa27b21cd9
new_patch_parent: e54ad7f1ee263ffa5a2de9c609d58dfa27b21cd9^
target_release: cf3069a14a9cccdd89d2b482f9eee5e37ebe25a6^
sanitizer: 
error_message: 
tag: CVE-2016-1583