project: fixmorph_bugs
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: eb132ccbdec5df46e29c9814adf76075ce83576b
new_patch_parent: eb132ccbdec5df46e29c9814adf76075ce83576b^
target_release: 228dae652188ab1e5ca96a6bb1adeb6acc2c43fd
sanitizer: 
error_message: 
tag: 214