project: tsbport
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: ba480dd4db9f1798541eb2d1c423fc95feee8d36
new_patch_parent: ba480dd4db9f1798541eb2d1c423fc95feee8d36^
target_release: e3f6c37c31522cc99cea96e0f0f6f536026fb058^
sanitizer: 
error_message: 
tag: CVE-2018-14612