project: linux
project_url: https://github.com/torvalds/linux/
new_patch: 8b8addf891de8a00e4d39fc32f93f7c5eb8feceb
new_patch_parent: 8b8addf891de8a00e4d39fc32f93f7c5eb8feceb^
target_release: 84f60bacb3084374a161bcb3e847dd22ed65f0a2^
sanitizer: 
error_message: 
tag: CVE-2016-3672