project: tsbport
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: b3ff8f1d380e65dddd772542aa9bff6c86bf715a
new_patch_parent: b3ff8f1d380e65dddd772542aa9bff6c86bf715a^
target_release: 1527c0e0229d2dd1c8ae1e73b1579bd8d5866b5b^
sanitizer: 
error_message: 
tag: CVE-2019-19377