project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 13ddaf26be324a7f951891ecd9ccd04466d27458
new_patch_parent: 16e96ba5e92ce06b54f0862d44bb27bfa00d6c23
target_release: None
sanitizer: 
error_message: 
tag: CVE-2024-26759