project: fixmorph_bugs
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: be5a1509af8dd8a78fea24a35fe4a82d4cd0ae70
new_patch_parent: be5a1509af8dd8a78fea24a35fe4a82d4cd0ae70^
target_release: 17743861edc71e01231b563eca750c89d0cf94db
sanitizer: 
error_message: 
tag: 180