project: fixmorph_bugs
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 5500598abbfb5b46201b9768bd9ea873a5eeaece
new_patch_parent: 5500598abbfb5b46201b9768bd9ea873a5eeaece^
target_release: 4ee24ae83ccbfb518be879617368f72db26dec6a
sanitizer: 
error_message: 
tag: 100