project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: 7dac4a1726a9c64a517d595c40e95e2d0d135f6f
new_patch_parent: dcae058a8da9c3cfc0055c7937ccd1a3dd0382a8
target_release: eea55da54d3e425d6a5f3cfeb3f26adbb0330354
sanitizer: 
error_message: 
tag: CVE-2018-1093