project: linux
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: ebe48d368e97d007bfeb76fcb065d6cfc4c96645
new_patch_parent: a3d9001b4e287fc043e5539d03d71a32ab114bcb
target_release: 2774edd43ab1f1c0e81c353502ccd5df59bfaeae
sanitizer: 
error_massage: 
tag: CVE-2022-27666