project: FreeRDP
project_url: https://github.com/FreeRDP/FreeRDP.git
new_patch: 5e5d27cf310e4c10b854be7667bfb7a5d774eb47
new_patch_parent: 9314b5492b501dbe6edb5430ee8d7c29ff772f68
target_release: a9ff85fc1edc9a3fd91f6cc728c076e4ce94d291
sanitizer: AddressSanitizer
error_message: "ERROR: AddressSanitizer"
tag: CVE-2024-32660