project: fixmorph_bugs
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: ebde1ca5a908b10312db4ecd7553e3ba039319ab
new_patch_parent: ebde1ca5a908b10312db4ecd7553e3ba039319ab^
target_release: 50d2b0e7c16314f4fc1ac1756f6835f8b02fe8af
sanitizer: 
error_message: 
tag: 3