project: linux
project_url: https://github.com/torvalds/linux/
new_patch: ab676b7d6fbf4b294bf198fb27ade5b0e865c7ce
new_patch_parent: ab676b7d6fbf4b294bf198fb27ade5b0e865c7ce^
target_release: 1ffc3cd9a36b504c20ce98fe5eeb5463f389e1ac^
sanitizer: 
error_message: 
tag: CVE-2016-0823