project: fixmorph_bugs
project_url: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/
new_patch: a28e4b2b18ccb90df402da3f21e1a83c9d4f8ec1
new_patch_parent: a28e4b2b18ccb90df402da3f21e1a83c9d4f8ec1^
target_release: 0a4cdc47f96f44c55cfa5a80ff383db2304dd734
sanitizer: 
error_message: 
tag: 241